/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ConstellationsRouteImport } from './routes/constellations'
import { Route as MoonsRouteImport } from './routes/moons'
import { Route as NebulaeRouteImport } from './routes/nebulae'
import { Route as PlanetsRouteImport } from './routes/planets'
import { Route as SkyRouteImport } from './routes/sky'
import { Route as ConstellationsIndexRouteImport } from './routes/constellations.index'
import { Route as ConstellationsSlugRouteImport } from './routes/constellations.$slug'
import { Route as MoonSlugRouteImport } from './routes/moon.$slug'
import { Route as NebulaSlugRouteImport } from './routes/nebula.$slug'
import { Route as PlanetSlugRouteImport } from './routes/planet.$slug'
import { Route as StarSlugRouteImport } from './routes/star.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstellationsRoute = ConstellationsRouteImport.update({
  id: '/constellations',
  path: '/constellations',
  getParentRoute: () => rootRouteImport,
} as any)
const MoonsRoute = MoonsRouteImport.update({
  id: '/moons',
  path: '/moons',
  getParentRoute: () => rootRouteImport,
} as any)
const NebulaeRoute = NebulaeRouteImport.update({
  id: '/nebulae',
  path: '/nebulae',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsRoute = PlanetsRouteImport.update({
  id: '/planets',
  path: '/planets',
  getParentRoute: () => rootRouteImport,
} as any)
const SkyRoute = SkyRouteImport.update({
  id: '/sky',
  path: '/sky',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstellationsIndexRoute = ConstellationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConstellationsRoute,
} as any)
const ConstellationsSlugRoute = ConstellationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConstellationsRoute,
} as any)
const MoonSlugRoute = MoonSlugRouteImport.update({
  id: '/moon/$slug',
  path: '/moon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NebulaSlugRoute = NebulaSlugRouteImport.update({
  id: '/nebula/$slug',
  path: '/nebula/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetSlugRoute = PlanetSlugRouteImport.update({
  id: '/planet/$slug',
  path: '/planet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StarSlugRoute = StarSlugRouteImport.update({
  id: '/star/$slug',
  path: '/star/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/classes': typeof ClassesRoute
  '/constellations': typeof ConstellationsRouteWithChildren
  '/moons': typeof MoonsRoute
  '/nebulae': typeof NebulaeRoute
  '/planets': typeof PlanetsRoute
  '/sky': typeof SkyRoute
  '/constellations/$slug': typeof ConstellationsSlugRoute
  '/moon/$slug': typeof MoonSlugRoute
  '/nebula/$slug': typeof NebulaSlugRoute
  '/planet/$slug': typeof PlanetSlugRoute
  '/star/$slug': typeof StarSlugRoute
  '/constellations/': typeof ConstellationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/classes': typeof ClassesRoute
  '/moons': typeof MoonsRoute
  '/nebulae': typeof NebulaeRoute
  '/planets': typeof PlanetsRoute
  '/sky': typeof SkyRoute
  '/constellations/$slug': typeof ConstellationsSlugRoute
  '/moon/$slug': typeof MoonSlugRoute
  '/nebula/$slug': typeof NebulaSlugRoute
  '/planet/$slug': typeof PlanetSlugRoute
  '/star/$slug': typeof StarSlugRoute
  '/constellations': typeof ConstellationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/classes': typeof ClassesRoute
  '/constellations': typeof ConstellationsRouteWithChildren
  '/moons': typeof MoonsRoute
  '/nebulae': typeof NebulaeRoute
  '/planets': typeof PlanetsRoute
  '/sky': typeof SkyRoute
  '/constellations/$slug': typeof ConstellationsSlugRoute
  '/moon/$slug': typeof MoonSlugRoute
  '/nebula/$slug': typeof NebulaSlugRoute
  '/planet/$slug': typeof PlanetSlugRoute
  '/star/$slug': typeof StarSlugRoute
  '/constellations/': typeof ConstellationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/classes'
    | '/constellations'
    | '/moons'
    | '/nebulae'
    | '/planets'
    | '/sky'
    | '/constellations/$slug'
    | '/moon/$slug'
    | '/nebula/$slug'
    | '/planet/$slug'
    | '/star/$slug'
    | '/constellations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/classes'
    | '/moons'
    | '/nebulae'
    | '/planets'
    | '/sky'
    | '/constellations/$slug'
    | '/moon/$slug'
    | '/nebula/$slug'
    | '/planet/$slug'
    | '/star/$slug'
    | '/constellations'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/classes'
    | '/constellations'
    | '/moons'
    | '/nebulae'
    | '/planets'
    | '/sky'
    | '/constellations/$slug'
    | '/moon/$slug'
    | '/nebula/$slug'
    | '/planet/$slug'
    | '/star/$slug'
    | '/constellations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  ClassesRoute: typeof ClassesRoute
  ConstellationsRoute: typeof ConstellationsRouteWithChildren
  MoonsRoute: typeof MoonsRoute
  NebulaeRoute: typeof NebulaeRoute
  PlanetsRoute: typeof PlanetsRoute
  SkyRoute: typeof SkyRoute
  MoonSlugRoute: typeof MoonSlugRoute
  NebulaSlugRoute: typeof NebulaSlugRoute
  PlanetSlugRoute: typeof PlanetSlugRoute
  StarSlugRoute: typeof StarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constellations': {
      id: '/constellations'
      path: '/constellations'
      fullPath: '/constellations'
      preLoaderRoute: typeof ConstellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moons': {
      id: '/moons'
      path: '/moons'
      fullPath: '/moons'
      preLoaderRoute: typeof MoonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nebulae': {
      id: '/nebulae'
      path: '/nebulae'
      fullPath: '/nebulae'
      preLoaderRoute: typeof NebulaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets': {
      id: '/planets'
      path: '/planets'
      fullPath: '/planets'
      preLoaderRoute: typeof PlanetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sky': {
      id: '/sky'
      path: '/sky'
      fullPath: '/sky'
      preLoaderRoute: typeof SkyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constellations/': {
      id: '/constellations/'
      path: '/'
      fullPath: '/constellations/'
      preLoaderRoute: typeof ConstellationsIndexRouteImport
      parentRoute: typeof ConstellationsRoute
    }
    '/constellations/$slug': {
      id: '/constellations/$slug'
      path: '/$slug'
      fullPath: '/constellations/$slug'
      preLoaderRoute: typeof ConstellationsSlugRouteImport
      parentRoute: typeof ConstellationsRoute
    }
    '/moon/$slug': {
      id: '/moon/$slug'
      path: '/moon/$slug'
      fullPath: '/moon/$slug'
      preLoaderRoute: typeof MoonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nebula/$slug': {
      id: '/nebula/$slug'
      path: '/nebula/$slug'
      fullPath: '/nebula/$slug'
      preLoaderRoute: typeof NebulaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planet/$slug': {
      id: '/planet/$slug'
      path: '/planet/$slug'
      fullPath: '/planet/$slug'
      preLoaderRoute: typeof PlanetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/star/$slug': {
      id: '/star/$slug'
      path: '/star/$slug'
      fullPath: '/star/$slug'
      preLoaderRoute: typeof StarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConstellationsRouteChildren {
  ConstellationsSlugRoute: typeof ConstellationsSlugRoute
  ConstellationsIndexRoute: typeof ConstellationsIndexRoute
}

const ConstellationsRouteChildren: ConstellationsRouteChildren = {
  ConstellationsSlugRoute: ConstellationsSlugRoute,
  ConstellationsIndexRoute: ConstellationsIndexRoute,
}

const ConstellationsRouteWithChildren = ConstellationsRoute._addFileChildren(
  ConstellationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  ClassesRoute: ClassesRoute,
  ConstellationsRoute: ConstellationsRouteWithChildren,
  MoonsRoute: MoonsRoute,
  NebulaeRoute: NebulaeRoute,
  PlanetsRoute: PlanetsRoute,
  SkyRoute: SkyRoute,
  MoonSlugRoute: MoonSlugRoute,
  NebulaSlugRoute: NebulaSlugRoute,
  PlanetSlugRoute: PlanetSlugRoute,
  StarSlugRoute: StarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
